# Generated by Django 4.2.4 on 2023-08-31 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default='NULL', max_length=10)),
                ('paneID', models.CharField(default='NULL', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
