# Generated by Django 4.2.4 on 2023-08-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stud_id',
            new_name='student_id',
        ),
    ]
