# Generated by Django 4.2.4 on 2023-09-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_profile_paneid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paneID',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
