# Generated by Django 4.2.4 on 2023-09-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
