# Generated by Django 4.2.4 on 2023-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_delete_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
