# Generated by Django 4.2.4 on 2023-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paneID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
