# Generated by Django 4.2.4 on 2023-08-16 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stdID', models.AutoField(primary_key=True, serialize=False)),
                ('stdFname', models.CharField(max_length=100)),
                ('stdLname', models.CharField(max_length=100)),
                ('stdEmail', models.EmailField(max_length=254)),
                ('stdMobile', models.CharField(max_length=10)),
                ('stdWhatsapp', models.CharField(max_length=10)),
                ('stdPassoutYear', models.PositiveIntegerField()),
                ('stdStream', models.CharField(max_length=100)),
                ('stdBranch', models.CharField(max_length=100)),
                ('stdGender', models.CharField(max_length=10)),
                ('stdDOB', models.DateField()),
                ('stdTriedStartupBefore', models.CharField(max_length=100)),
                ('stdFamBackground', models.TextField()),
                ('stdEBC', models.TextField()),
                ('stdAadhar', models.CharField(max_length=14)),
                ('stdAddress', models.TextField()),
                ('stdAddrPin', models.CharField(max_length=6)),
                ('stdAddrCity', models.CharField(max_length=100)),
                ('stdAddrTaluka', models.CharField(max_length=100)),
                ('stdAddrDist', models.CharField(max_length=100)),
                ('stdAddrState', models.CharField(max_length=100)),
                ('stdAddrCountry', models.CharField(max_length=100)),
                ('stdBelongsTo', models.CharField(max_length=100)),
                ('recordCreatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordCreatedBy', models.CharField(default='system', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='system', max_length=100)),
            ],
        ),
    ]
