# Generated by Django 4.2.4 on 2023-08-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stdEduLoan',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stdInstiID',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='stdParentSupport',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='recordCreatedBy',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='recordUpdatedBy',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
