# Generated by Django 4.2.4 on 2023-08-18 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0002_student_stdeduloan_student_stdinstiid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('panelID', models.AutoField(primary_key=True, serialize=False)),
                ('panelistFname', models.CharField(max_length=100)),
                ('panelistLname', models.CharField(max_length=100)),
                ('panelistDOB', models.DateField()),
                ('panelistGender', models.CharField(max_length=10)),
                ('panelistEmail', models.EmailField(max_length=254)),
                ('panelistMobile', models.CharField(max_length=10)),
                ('panelistWhatsapp', models.CharField(max_length=10)),
                ('stdAadhar', models.CharField(max_length=14)),
                ('panelistInstiID', models.CharField(max_length=100)),
                ('panelistDomain', models.CharField(max_length=100)),
                ('panelistDegree', models.CharField(max_length=100)),
                ('panelistDesignation', models.CharField(max_length=100)),
                ('panelistTotalExp', models.CharField(max_length=100)),
                ('panelistIdeaEvaluated', models.CharField(max_length=100)),
                ('panelistStatus', models.CharField(max_length=100)),
                ('recordCreatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordCreatedBy', models.CharField(default='admin', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
