# Generated by Django 4.2.4 on 2023-08-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0003_panelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panelist',
            old_name='stdAadhar',
            new_name='panelistAadhar',
        ),
    ]
