# Generated by Django 4.2.4 on 2023-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0004_rename_stdaadhar_panelist_panelistaadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='panelistStatus',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
