# Generated by Django 4.0.3 on 2023-08-19 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0005_alter_panelist_paneliststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('instID', models.AutoField(primary_key=True, serialize=False)),
                ('instName', models.CharField(max_length=100)),
                ('instType', models.CharField(max_length=100)),
                ('instStream', models.CharField(max_length=100)),
                ('instNoOfStudents', models.CharField(max_length=100)),
                ('instAddress', models.CharField(max_length=100)),
                ('instPin', models.CharField(max_length=100)),
                ('instCity', models.CharField(max_length=100)),
                ('instTaluka', models.CharField(max_length=100)),
                ('instDist', models.CharField(max_length=100)),
                ('instState', models.CharField(max_length=100)),
                ('instCountry', models.CharField(max_length=100)),
                ('instSPOCFname', models.CharField(max_length=100)),
                ('instSPOCLname', models.CharField(max_length=100)),
                ('instSPOCEmail', models.EmailField(max_length=254)),
                ('instSPOCMobile', models.CharField(max_length=10)),
                ('instSPOCWhatsapp', models.CharField(max_length=10)),
                ('instSPOCWeb', models.TextField()),
                ('instIncubator', models.CharField(default='no', max_length=100)),
                ('instEDC', models.CharField(default='no', max_length=100)),
                ('instIIC', models.CharField(default='no', max_length=100)),
                ('instARIIA', models.CharField(max_length=100)),
                ('instNIRF', models.CharField(max_length=100)),
                ('instNAAC', models.CharField(max_length=100)),
                ('instNBA', models.CharField(max_length=100)),
                ('recordCreatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordCreatedBy', models.CharField(default='admin', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
