# Generated by Django 4.0.3 on 2023-08-19 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0006_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubators',
            fields=[
                ('incuID', models.AutoField(primary_key=True, serialize=False)),
                ('incuName', models.CharField(max_length=100)),
                ('incuType', models.TextField()),
                ('incuSupportedBy', models.TextField()),
                ('incuFundAvailable', models.CharField(max_length=10)),
                ('incuAddress', models.TextField()),
                ('incuCity', models.CharField(max_length=100)),
                ('incuTaluka', models.CharField(max_length=100)),
                ('incuDist', models.CharField(max_length=100)),
                ('incuState', models.CharField(max_length=100)),
                ('incuCountry', models.CharField(max_length=100)),
                ('incuPin', models.CharField(max_length=6)),
                ('incuSPOCFname', models.CharField(max_length=100)),
                ('incuSPOCLname', models.CharField(max_length=100)),
                ('incuSPOCEmail', models.EmailField(max_length=254)),
                ('incuSPOCMobile', models.CharField(max_length=10)),
                ('incuSPOCWhatsapp', models.CharField(max_length=10)),
                ('incuSPOCWeb', models.TextField()),
                ('recordCreatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordCreatedBy', models.CharField(default='admin', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
