# Generated by Django 4.0.3 on 2023-08-20 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0007_incubators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('catalystID', models.AutoField(primary_key=True, serialize=False)),
                ('catalystFname', models.CharField(max_length=100)),
                ('catalystLname', models.CharField(max_length=100)),
                ('catalystEmail', models.EmailField(max_length=254)),
                ('catalystMobile', models.CharField(max_length=10)),
                ('catalystWhatsapp', models.CharField(max_length=10)),
                ('catalystYear', models.CharField(max_length=10)),
                ('catalystStreamBranch', models.CharField(max_length=100)),
                ('catalystGender', models.CharField(max_length=100)),
                ('catalystDOB', models.DateField()),
                ('catalystTriedStartupBefore', models.CharField(max_length=100)),
                ('catalystFamilyBackground', models.CharField(max_length=100)),
                ('catalystEBC', models.CharField(max_length=100)),
                ('catalystAadhar', models.CharField(max_length=14)),
                ('catalystAddress', models.CharField(max_length=100)),
                ('catalystPin', models.CharField(max_length=6)),
                ('catalystCity', models.CharField(max_length=100)),
                ('catalystTaluka', models.CharField(max_length=100)),
                ('catalystDist', models.CharField(max_length=100)),
                ('catalystState', models.CharField(max_length=100)),
                ('catalystCountry', models.CharField(max_length=100)),
                ('catalystBelongsTo', models.CharField(max_length=100)),
                ('recordCreatedBy', models.CharField(default='admin', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
