# Generated by Django 4.0.3 on 2023-08-20 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0008_catalyst'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalyst',
            name='recordCreatedOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
