# Generated by Django 4.2.4 on 2023-08-22 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0009_catalyst_recordcreatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('teamCEO', models.CharField(max_length=100)),
                ('teamCOO', models.CharField(max_length=100)),
                ('teamCMO', models.CharField(max_length=100)),
                ('teamCTO', models.CharField(max_length=100)),
                ('teamCFO', models.CharField(max_length=100)),
                ('teamInstiID', models.CharField(default='1', max_length=100)),
                ('recordCreatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordCreatedBy', models.CharField(default='admin', max_length=100)),
                ('recordUpdatedOn', models.DateField(default=django.utils.timezone.now)),
                ('recordUpdatedBy', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
