# Generated by Django 4.1.1 on 2023-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0009_catalyst_recordcreatedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalyst',
            name='catalystType',
            field=models.CharField(default='default_value_here', max_length=100),
        ),
    ]
