# Generated by Django 4.2.4 on 2023-08-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0010_catalyst_catalysttype'),
        ('studRegistration', '0010_team'),
    ]

    operations = [
    ]
