<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-26 10:48
=======
# Generated by Django 4.1.1 on 2023-08-24 13:25
>>>>>>> 9eb2b78b4b3c638d46fb835e19729aff99cc1bfd

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0010_catalyst_catalysttype'),
        ('studRegistration', '0010_team'),
    ]

    operations = [
    ]
