# Generated by Django 4.1.1 on 2023-08-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0010_catalyst_catalysttype'),
        ('studRegistration', '0010_team'),
    ]

    operations = [
    ]
