# Generated by Django 4.2.4 on 2023-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0015_alter_student_stddob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdDOB',
            field=models.DateField(),
        ),
    ]
