# Generated by Django 4.0.3 on 2023-10-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0016_alter_student_stddob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teamID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studRegistration.team'),
        ),
    ]
