# Generated by Django 4.2.4 on 2023-10-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0018_alter_student_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdInstiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studRegistration.institute'),
        ),
    ]
