# Generated by Django 4.1.1 on 2024-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0028_alter_student_stduniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelist',
            name='panelistDOB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdDOB',
            field=models.CharField(max_length=10),
        ),
    ]
