# Generated by Django 4.1.1 on 2024-01-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0030_alter_student_stddob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdDOB',
            field=models.DateField(),
        ),
    ]
