# Generated by Django 4.1.1 on 2024-01-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0031_alter_student_stddob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdDOB',
            field=models.CharField(max_length=10),
        ),
    ]
