# Generated by Django 4.1.1 on 2024-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0034_alter_student_stddob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stdEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
