# Generated by Django 4.2.4 on 2024-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0035_student_stdemailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamUniqueID',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
