# Generated by Django 5.0.4 on 2024-06-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_correct_answer'),
        ('studRegistration', '0036_team_teamuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studRegistration.student'),
        ),
    ]
