# Generated by Django 5.0.4 on 2024-06-03 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizresult_student_alter_quizresult_user_id'),
        ('studRegistration', '0036_team_teamuniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studRegistration.student'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
