# Generated by Django 5.0.4 on 2024-06-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_student_quizresult_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='student_id',
            new_name='student',
        ),
    ]
