# Generated by Django 4.2.4 on 2023-12-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_ideaeval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdeaEval',
        ),
    ]
