# Generated by Django 4.2.4 on 2024-02-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_ideasub_ideateamid_ideasub_teamuniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideasub',
            old_name='teamUniqueID',
            new_name='ideaUniqueID',
        ),
    ]
