# Generated by Django 4.2.4 on 2024-02-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0036_team_teamuniqueid'),
        ('idea', '0006_rename_teamuniqueid_ideasub_ideauniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasub',
            name='ideaTeamInstiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studRegistration.institute'),
        ),
    ]
