# Generated by Django 4.2.4 on 2024-02-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studRegistration', '0036_team_teamuniqueid'),
        ('idea', '0008_ideasub_ideastatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasub',
            name='ideaTeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studRegistration.team', to_field='teamUniqueID'),
        ),
    ]
