# Generated by Django 4.2.4 on 2024-02-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_alter_ideasub_ideateamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamCEO',
        ),
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamCFO',
        ),
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamCMO',
        ),
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamCOO',
        ),
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamCTO',
        ),
        migrations.RemoveField(
            model_name='ideasub',
            name='ideaTeamInstiID',
        ),
    ]
