# Generated by Django 5.0.2 on 2024-05-29 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0011_ideasub_panelistid'),
        ('studRegistration', '0036_team_teamuniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasub',
            name='panelistID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studRegistration.panelist'),
        ),
    ]
