# Generated by Django 4.0.3 on 2024-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0013_ideaeval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideaeval',
            name='evalAreaOfImprov',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ideaeval',
            name='evalOverallFeedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ideaeval',
            name='evalRecommendedToIncu',
            field=models.BooleanField(default=False),
        ),
    ]
