# Generated by Django 4.0.3 on 2024-06-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0015_alter_ideaeval_evalrecommendedtoincu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaeval',
            name='ideaTeamPSdetail',
            field=models.TextField(default=''),
        ),
    ]
