# Generated by Django 4.0.3 on 2024-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0016_ideaeval_ideateampsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideaeval',
            name='ideaID',
            field=models.CharField(default='default_ideaID', max_length=100),
        ),
    ]
