# Generated by Django 5.0.2 on 2024-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0017_ideaeval_ideaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasub',
            name='evaluateStatus',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
